/**
 * Comprehensive Bengali to English mapping for Bangladesh geographic data
 * Generated by aligning bangladesh-divisions.ts and bangladesh-divisions-bn.ts
 */

// Division mappings (8 divisions)
export const bengaliToEnglishDivision: Record<string, string> = {
  'খুলনা': 'Khulna',
  'চট্টগ্রাম': 'Chattogram',
  'ঢাকা': 'Dhaka',
  'বরিশাল': 'Barishal',
  'ময়মনসিংহ': 'Mymensingh',
  'রংপুর': 'Rangpur',
  'রাজশাহী': 'Rajshahi',
  'সিলেট': 'Sylhet',
};

// District mappings (64 districts)
export const bengaliToEnglishDistrict: Record<string, string> = {
  'কক্সবাজার': "Cox's Bazar",
  'কিশোরগঞ্জ': 'Kishoreganj',
  'কুড়িগ্রাম': 'Kurigram',
  'কুমিল্লা': 'Cumilla',
  'কুষ্টিয়া': 'Kushtia',
  'খাগড়াছড়ি': 'Khagrachhari',
  'খুলনা': 'Khulna',
  'গাইবান্ধা': 'Gaibandha',
  'গাজীপুর': 'Gazipur',
  'গোপালগঞ্জ': 'Gopalganj',
  'চট্টগ্রাম': 'Chattogram',
  'চাঁদপুর': 'Chandpur',
  'চাঁপাইনবাবগঞ্জ': 'Chapainawabganj',
  'চুয়াডাঙ্গা': 'Chuadanga',
  'জয়পুরহাট': 'Joypurhat',
  'জামালপুর': 'Jamalpur',
  'ঝালকাঠি': 'Jhalokati',
  'ঝিনাইদহ': 'Jhenaidah',
  'টাঙ্গাইল': 'Tangail',
  'ঠাকুরগাঁও': 'Thakurgaon',
  'ঢাকা': 'Dhaka',
  'দিনাজপুর': 'Dinajpur',
  'নওগাঁ': 'Naogaon',
  'নড়াইল': 'Narail',
  'নরসিংদী': 'Narsingdi',
  'নাটোর': 'Natore',
  'নারায়ণগঞ্জ': 'Narayanganj',
  'নীলফামারী': 'Nilphamari',
  'নেত্রকোণা': 'Netrokona',
  'নোয়াখালী': 'Noakhali',
  'পঞ্চগড়': 'Panchagarh',
  'পটুয়াখালী': 'Patuakhali',
  'পাবনা': 'Pabna',
  'পিরোজপুর': 'Pirojpur',
  'ফরিদপুর': 'Faridpur',
  'ফেনী': 'Feni',
  'বগুড়া': 'Bogura',
  'বরগুনা': 'Barguna',
  'বরিশাল': 'Barishal',
  'বাগেরহাট': 'Bagerhat',
  'বান্দরবান': 'Bandarban',
  'ব্রাহ্মণবাড়িয়া': 'Brahmanbaria',
  'ভোলা': 'Bhola',
  'ময়মনসিংহ': 'Mymensingh',
  'মাগুরা': 'Magura',
  'মাদারীপুর': 'Madaripur',
  'মানিকগঞ্জ': 'Manikganj',
  'মুন্সীগঞ্জ': 'Munshiganj',
  'মেহেরপুর': 'Meherpur',
  'মৌলভীবাজার': 'Moulvibazar',
  'যশোর': 'Jashore',
  'রংপুর': 'Rangpur',
  'রাঙ্গামাটি': 'Rangamati',
  'রাজবাড়ী': 'Rajbari',
  'রাজশাহী': 'Rajshahi',
  'লক্ষ্মীপুর': 'Lakshmipur',
  'লালমনিরহাট': 'Lalmonirhat',
  'শরীয়তপুর': 'Shariatpur',
  'শেরপুর': 'Sherpur',
  'সাতক্ষীরা': 'Satkhira',
  'সিরাজগঞ্জ': 'Sirajganj',
  'সিলেট': 'Sylhet',
  'সুনামগঞ্জ': 'Sunamganj',
  'হবিগঞ্জ': 'Habiganj',
};

// Thana mappings (will be populated on-demand for now to avoid duplicates)
// Only commonly used thanas are included
export const bengaliToEnglishThana: Record<string, string> = {
  // Pabna District (from user's example)
  'ভাঙ্গুড়া': 'Bhangura',
  'পাবনা সদর': 'Pabna Sadar',
  'আটঘরিয়া': 'Atgharia',
  'বেড়া': 'Bera',
  'চাটমোহর': 'Chatmohar',
  'ঈশ্বরদী': 'Ishwardi',
  'সাঁথিয়া': 'Santhia',
  'সুজানগর': 'Sujanagar',

  // More will be added as needed
};

export const getEnglishDivisionName = (bengaliName: string): string => {
  return bengaliToEnglishDivision[bengaliName] || bengaliName;
};

export const getEnglishDistrictName = (bengaliName: string): string => {
  return bengaliToEnglishDistrict[bengaliName] || bengaliName;
};

export const getEnglishThanaName = (bengaliName: string): string => {
  return bengaliToEnglishThana[bengaliName] || bengaliName;
};
